### ISSUE TITLE
Home Page Management

### ISSUE THREAD

**Issue by dnelband** [TorunW/Juedische-Stimme#15]
should we create a way to manage the home page layout, only the order of the modules and or free text modules that could be featured somewhere? need to talk abou this with the JS team

**Comment by TorunW** [comment]
Do you mean if they should be able to move around and change the order of each component? Like change order on aktuelles and über uns section?

**Comment by dnelband** [comment]
yes something like that, or / and enable adding a costum section? like the about us for example

**Comment by TorunW** [comment]
For the general page layout, no
About section could use a customize functionality as they might want to expand that section in the future.
