### ISSUE TITLE
Component/Posts.tsx

### ISSUE THREAD

**Issue by dnelband** [TorunW/Juedische-Stimme#28]
- [x] create a new folder in components - posts, inside of it we should have - Posts.tsx (list of posts) PostPage.tsx ( formerly Post.tsx. is the view of a single post when we are on a post page, i.e article page ), and Post.tsx ( list item in the Posts.tsx ), everything between line 20 - 84 needs to be in Post.tsx.
- [x] do not use specific names like aktuelles and newsletter for styling class names, use something generic like  twoColumns / threeColumns instead

**Comment by TorunW** [comment]
There is already a Post.tsx, should this be in that component?

**Comment by dnelband** [comment]
should be
components/posts/PostPage.tsx
components/posts/Posts.tsx ( you can call it PostList if you prefer)
components/posts/Post.tsx ( you can call it PostListItem if you prefer)

another option would be to ommit the word "post" from the names and just have Page, List, ListItem. but you can choose whatever seems the best for you

**Comment by TorunW** [comment]
done
