### ISSUE TITLE
Facebook Feed / Events

### ISSUE THREAD

**Issue by dnelband** [TorunW/Juedische-Stimme#6]
components/FacebookFeed & componenets/FacebookEvents

- [x] FEED - every fb feed post has generally speaking an image. inside the fbPost objects ( FacebookFeed.js feedDisplay map function items) there are two options:  fbPost.full_picture attribute or / and an attachments array ( usually with one object ). make sure you show an image on every facebook post in either case
- [x] FEED/EVENTS - trim text to fit with the design
- [x] FEED/EVENTS - implement design
- [x] convert to ts when done implementing design
- [x] Formate date on Events

**Comment by TorunW** [comment]
@dnelband I've asked if previous events really should be shown, I think its confusing for whoever is the viewer, and only showing upcoming events makes more sense. I'm waiting for their answer on this.

**Comment by TorunW** [comment]
I don't think a slideshow is useful if the post has more than one image, a post should just be a preview and I believe they rather have users click on the post to see it in full on Facebook directly as this will encourage the user to comment and share. @dnelband

**Comment by TorunW** [comment]
@dnelband I need for the post:

- [ ] Author
- [ ] Author profile image (JS Logo)
- [ ] Time ago posted
- [ ] Amount of likes, shares and comments
- [ ] Share option (this should have the possibility to share to both Facebook and twitter if possible)

Please @ me on the checklist items I should do

**Comment by dnelband** [comment]
@TorunW 
this url will generate the profile image:
http://graph.facebook.com/[ID OF FACEBOOK PROFILE / PAGE ]/picture?type=square
http://graph.facebook.com/998665673528998/picture?type=square

**Comment by dnelband** [comment]
- [ ] make the links to the facebook posts pages open in a new tab

**Comment by TorunW** [comment]
- [ ] Likes display, it should be in the JSON we get from Facebook under 'reactions'. I cannot find that anywhere. 
- [ ] Hide the broken Facebook posts (yours or my to-do?)
@dnelband

**Comment by TorunW** [comment]
@dnelband 
The reason some posts aren't displayed properly is because it's a share of a share of a share, right? I can communicate this to JS so they are aware of it.
For now lets keep the amount of posts until I'm done with the CSS, after that they said 3 Facebook's Posts are enough.

**Comment by TorunW** [comment]
- [ ] On events, only display upcoming

**Comment by dnelband** [comment]
i have not been able to get likes in the feed, even when i try to fetch likes per single post, im not getting anywhere near the real count, mostly its 0 and sometimes its 1, its never the right number, so i think it will be better not to show the like count at all

**Comment by dnelband** [comment]
the links for the Comment / Share / Like action are inside the "actions" property of the fbPost.

**Comment by TorunW** [comment]
Okey, I think in worst case then we won't show any of the 3, it's a bit weird to have shares and comments but not the likes. Probably makes more sense to just have the "view on Facebook" and "share". 
Lets see though, and I'll ask the girls

**Comment by dnelband** [comment]
ok so ive finally added likes & comments count to the fb posts - post.likes.summary.total_count, post.comments.summary.total_count
